# Generated by Django 4.2.6 on 2023-10-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
